#!/bin/bash
# ==========================================
green='\e[1;34m'
NC='\e[0m'

cd /root/
systemctl restart stunnel5
cd
echo -e "\e[1;34m         Success...\e[0m"
sleep 2
clear
echo -e "\e[1;34m         Fix Finish Back To Menu Please Wait...\e[0m"
sleep 3
clear
menu
